
spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:mariadb://housingsubscription.ccny9xairkls.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: ssu12345